### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Mathias88** [guillaumebriday/laravel-blog#29]
I ask you a question for a doubt that I have, why do you use the fields posted_at or registered_at instead of created_at?

**Comment by guillaumebriday** [comment]
Hey ! 

I use posted_at to be able to publish post in the futur.

And by experience I don't like to rely on `created_at` and `updated_at` fields because it's handle by laravel itself and I do not have control on this fields.

If you export your data and import it again with a script, this fields will be override.
